// AUTO-GENERATED by tools/gen_native_frame_tables_ts.py from
// schema/wire_protocol.json - do not hand-edit. Re-run `python3
// tools/gen_native_frame_tables_ts.py` after any wire_protocol.json change
// and commit the result (see spec/SCHEMA_GOVERNANCE.md).
//
// The single source of truth for frame-type numbers, the STX byte, the
// native protocol version, and the telemetry/command wire field layout -
// every consumer (motor/display firmware, web tooling) is generated
// from/checked against this same schema, instead of each hand-typing
// these numbers independently. Consumed by native-frame-codec.ts here,
// and by any TypeScript tooling that needs the same field layout.

export const NATIVE_STX = 0x43;
export const NATIVE_PROTOCOL_VERSION = 1;
export const NATIVE_MAX_PAYLOAD = 255;

export const NATIVE_FRAME_TYPES = {
  ALIVE: 0,
  PERIODIC: 1,
  COMMAND: 2,
  CONFIGURATION: 3,
  CAPABILITY: 4,
  CONFIG_READ: 5,
} as const;

export interface NativeWireField {
  signal: string;
  offset: number;
  width: number;
}

/** g_native_telemetry_fields (native_frame.c) - motor -> display broadcast, wire order. */
export const TELEMETRY_FIELDS: readonly NativeWireField[] = [
  { signal: "WHEEL_SPEED_KMH_X10", offset: 0, width: 2 },
  { signal: "POWER_W", offset: 2, width: 2 },
  { signal: "SOC_PERCENT", offset: 4, width: 1 },
  { signal: "FAULT_BITMASK", offset: 5, width: 1 },
  { signal: "ASSIST_LEVEL", offset: 6, width: 1 },
  { signal: "LIGHTS_ON", offset: 7, width: 1 },
  { signal: "MOTOR_OUTPUT_DUTY", offset: 8, width: 1 },
  { signal: "PEDAL_CADENCE_RAW", offset: 9, width: 2 },
  { signal: "BATTERY_VOLTAGE_X10", offset: 11, width: 2 },
  { signal: "BATTERY_CURRENT_RAW_X10", offset: 13, width: 2 },
  { signal: "MOTOR_TEMPERATURE_RAW", offset: 15, width: 2 },
  { signal: "WHEEL_SPEED_RAW_TICKS", offset: 17, width: 2 },
  { signal: "THROTTLE_RAW", offset: 19, width: 1 },
  { signal: "PEDAL_TORQUE_RAW", offset: 20, width: 2 },
  { signal: "MOTOR_SPEED_ERPS", offset: 22, width: 2 },
  { signal: "PEDAL_TORQUE_ADC_RAW", offset: 24, width: 2 },
  { signal: "HUMAN_POWER_W", offset: 26, width: 2 },
];

/** g_native_command_fields (native_frame.c) - display -> motor, wire order. */
export const COMMAND_FIELDS: readonly NativeWireField[] = [
  { signal: "ASSIST_LEVEL", offset: 0, width: 1 },
  { signal: "LIGHTS_ON", offset: 1, width: 1 },
  { signal: "WALK_ASSIST_ENGAGE", offset: 2, width: 1 },
];

