#!/usr/bin/env python3
"""Generate codec/ts/native-frame-tables.ts from schema/wire_protocol.json -
the single source of truth every consumer (motor/display firmware, web
tooling) is meant to be generated from or checked against
(spec/SCHEMA_GOVERNANCE.md).

A consumer project vendors this repo (typically as a git submodule under
vendor/) and imports codec/ts/*.ts directly; it does not need to re-run
this script unless it wants to regenerate this repo's own committed output
after a schema/wire_protocol.json change here.

Why this exists: without a generated table, TypeScript tooling that needs
to build or parse a native frame (a bench motor emulator, a live
config-write client, a web-based flashing tool) tends to hand-type the
frame-type numbers/STX/protocol version as bare number literals,
independently in each place that needs them - each an opportunity to
drift from the real wire format the same way a hand-ported CRC16/
frame-build implementation can. This generator makes that drift
structurally impossible for the constants it covers.

Does NOT cover the CRC16/frame-build byte math itself - that's hand-
written once, shared, in native-frame-codec.ts (a TypeScript sibling of
codec/c/native_protocol.c), not code-generated here; see that file's own
header comment for why.

Run from this repo's root:  python3 tools/gen_native_frame_tables_ts.py
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
SCHEMA_JSON = os.path.join(REPO_ROOT, "schema", "wire_protocol.json")
OUT_TS = os.path.join(REPO_ROOT, "codec", "ts", "native-frame-tables.ts")


def ts_field_table(rows):
    lines = ["["]
    for r in rows:
        lines.append(f'  {{ signal: "{r["signal"]}", offset: {r["offset"]}, width: {r["width"]} }},')
    lines.append("]")
    return "\n".join(lines)


def main():
    with open(SCHEMA_JSON, "r", encoding="utf-8") as f:
        schema = json.load(f)

    out = []
    out.append("// AUTO-GENERATED by tools/gen_native_frame_tables_ts.py from")
    out.append("// schema/wire_protocol.json - do not hand-edit. Re-run `python3")
    out.append("// tools/gen_native_frame_tables_ts.py` after any wire_protocol.json change")
    out.append("// and commit the result (see spec/SCHEMA_GOVERNANCE.md).")
    out.append("//")
    out.append("// The single source of truth for frame-type numbers, the STX byte, the")
    out.append("// native protocol version, and the telemetry/command wire field layout -")
    out.append("// every consumer (motor/display firmware, web tooling) is generated")
    out.append("// from/checked against this same schema, instead of each hand-typing")
    out.append("// these numbers independently. Consumed by native-frame-codec.ts here,")
    out.append("// and by any TypeScript tooling that needs the same field layout.")
    out.append("")
    out.append(f"export const NATIVE_STX = {schema['stx']};")
    out.append(f"export const NATIVE_PROTOCOL_VERSION = {schema['protocol_version']};")
    out.append(f"export const NATIVE_MAX_PAYLOAD = {schema['max_payload']};")
    out.append("")
    out.append("export const NATIVE_FRAME_TYPES = {")
    for name, value in schema["frame_types"].items():
        out.append(f"  {name}: {value},")
    out.append("} as const;")
    out.append("")
    out.append("export interface NativeWireField {")
    out.append("  signal: string;")
    out.append("  offset: number;")
    out.append("  width: number;")
    out.append("}")
    out.append("")
    out.append("/** g_native_telemetry_fields (native_frame.c) - motor -> display broadcast, wire order. */")
    out.append(f"export const TELEMETRY_FIELDS: readonly NativeWireField[] = {ts_field_table(schema['telemetry_fields'])};")
    out.append("")
    out.append("/** g_native_command_fields (native_frame.c) - display -> motor, wire order. */")
    out.append(f"export const COMMAND_FIELDS: readonly NativeWireField[] = {ts_field_table(schema['command_fields'])};")
    out.append("")

    with open(OUT_TS, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {OUT_TS} ({len(schema['frame_types'])} frame types, "
          f"{len(schema['telemetry_fields'])} telemetry fields, "
          f"{len(schema['command_fields'])} command fields)")


if __name__ == "__main__":
    main()
