#!/usr/bin/env python3
"""Generate codec/c/native_telemetry_offsets.h from schema/wire_protocol.json
- named wire-offset/width constants for the native protocol's telemetry and
command fields (spec/SCHEMA_GOVERNANCE.md).

A consumer project vendors this repo (typically as a git submodule under
vendor/) and includes codec/c/*.h directly; it does not need to re-run this
script unless it wants to regenerate this repo's own committed output
after a schema/wire_protocol.json change here.

Why this exists: without a generated offset table, a display firmware's
frame parser tends to hardcode each field's wire offset as a bare integer
literal (`if (payload_len >= 17) { ... p[15] ... }`), independently of
whatever table on the motor side those exact same numbers come from - with
no way to notice if the motor's wire layout ever changes out from under
it. These generated #defines are the single source for each field's
(offset, width) pair; a parser reads via native_field_read_raw(p,
payload_len, NATIVE_TELEM_OFFSET_X, NATIVE_TELEM_WIDTH_X, &v) (this
repo's own codec's length-gated read, codec/c/native_protocol.h) instead
of hand-rolled `if (payload_len >= N)` bounds checks with
independently-typed-in offsets.

Run from this repo's root:  python3 tools/gen_native_telemetry_offsets_h.py
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
SCHEMA_JSON = os.path.join(REPO_ROOT, "schema", "wire_protocol.json")
OUT_H = os.path.join(REPO_ROOT, "codec", "c", "native_telemetry_offsets.h")


def emit_defines(out, prefix, rows):
    for r in rows:
        out.append(f"#define {prefix}_{r['signal']}_OFFSET {r['offset']}u")
        out.append(f"#define {prefix}_{r['signal']}_WIDTH {r['width']}u")


def main():
    with open(SCHEMA_JSON, "r", encoding="utf-8") as f:
        schema = json.load(f)

    out = []
    out.append("/* AUTO-GENERATED by tools/gen_native_telemetry_offsets_h.py from")
    out.append(" * schema/wire_protocol.json - do not edit by hand. Re-run")
    out.append(" * `python3 tools/gen_native_telemetry_offsets_h.py` after any")
    out.append(" * wire_protocol.json change and commit the result (see")
    out.append(" * spec/SCHEMA_GOVERNANCE.md).")
    out.append(" *")
    out.append(" * Named wire offset/width constants for every native-protocol telemetry")
    out.append(" * and command field, in the schema's own field order. Use with the shared")
    out.append(" * codec's native_field_read_raw() (native_protocol.h)")
    out.append(" * instead of hardcoding a field's byte offset independently. */")
    out.append("")
    out.append("#ifndef NATIVE_TELEMETRY_OFFSETS_H")
    out.append("#define NATIVE_TELEMETRY_OFFSETS_H")
    out.append("")
    out.append("/* Telemetry fields - motor -> display broadcast. */")
    emit_defines(out, "NATIVE_TELEM", schema["telemetry_fields"])
    out.append("")
    out.append("/* Command fields - display -> motor. */")
    emit_defines(out, "NATIVE_CMD", schema["command_fields"])
    out.append("")
    out.append("#endif /* NATIVE_TELEMETRY_OFFSETS_H */")
    out.append("")

    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"wrote {OUT_H} ({len(schema['telemetry_fields'])} telemetry fields, "
          f"{len(schema['command_fields'])} command fields)")


if __name__ == "__main__":
    main()
